### ISSUE TITLE
MIDI files for AugmentedNet

### ISSUE THREAD

**Issue by adityac95** [napulen/AugmentedNet#78]
Hi Nestor, you replied to my tweet seeking help with automatic chord annotation tools – thanks for offering to help me with AugmentedNet! 

I’m hoping to generate chord annotations on a popular music MIDI dataset. I’m not certain that *all* of it was generated from notation, but for the most part when I load files into MuseScore or Sibelius they read fairly well. So I’m minded to try both versions 1.7.0 and 1.5.1 as you suggested. You mentioned a parser would be necessary for 1.5.1; is that something you have to hand or do you recommend any particular parsers that you've previously encountered?

I appreciate your help.

**Comment by napulen** [comment]
Hey @adityac95! Yup, I remember.

> I’m hoping to generate chord annotations on a popular music MIDI dataset. I’m not certain that *all* of it was generated from notation, but for the most part when I load files into MuseScore or Sibelius they read fairly well. 

Those are great news! Both of those notation software have ways to do batch conversion, so if that's possible for your dataset (I don't know how big it is), then please try to batch convert to MusicXML. That'd vastly simplify things. Just pass the folder with MusicXMLs to `v1.7.0`, with something like:

```python
(.env) $ python -m AugmentedNet.inference --dir <folder_with_musicxmls>
```

and optionally `--useGpu` if you have a GPU.

> So I’m minded to try both versions 1.7.0 and 1.5.1 as you suggested.

`v1.7.0` is much much more accurate. If it's possible to run that one, I'd recommend it. The reason why I mentioned `v1.5.1` as a fallback is that `v1.7.0` needs measure and duration info, which only makes sense for something like `MusicXML`, whereas `v1.5.1` is more generic. The data could run on regular MIDI files, but I'd probably need to write some patch for it.

Let's try with the `v1.7.0` first, if you can do the batch conversion. 

If that doesn't work out, let me know, and I'll check the alternative path.

Cheers.

**Comment by napulen** [comment]
On the experiments, this network outperforms Harmony Transformer v2, by the way. Worth the try.

**Comment by adityac95** [comment]
Thanks for your help! I've successfully managed to use the pretrained version to predict chords annotations in my dataset. I'm surprised at how poor some of the predictions are, even though much of my dataset is highly triadic. I wonder if this has something to do with the model being trained on classical rather than popular music, since the functional harmonic logic is different in these styles. I'll keep experimenting, though!

**Comment by napulen** [comment]
Can you share one of the "bad" examples (input MusicXML or original MIDI or screenshot of a section with poor results)?

Genre has some effect, but it should handle a highly triadic dataset. I'm leaning more towards data loading/encoding problems. Seeing an example would help triaging.

**Comment by napulen** [comment]
If you prefer we can do this over email (napulen at gmail).

**Comment by napulen** [comment]
Hi @adityac95 

Based on the examples provided, I determined that percussion tracks **do** hinder the performance of the model (see #79), because they introduce nonsensical pitch information.

A fix is in place #80.

A new release is coming right up with this change.

There was a noticeable improvement with the fix. This is on a version I found online of the track you mentioned (drumtrack highlighted):

![image](https://user-images.githubusercontent.com/7258463/174658391-27526117-629b-4416-8148-266ac9d5255d.png)

And the analysis before and after the patch:

![image](https://user-images.githubusercontent.com/7258463/174658469-2b6b11e4-259b-48e1-84b1-ce934d9dac94.png)

**Comment by adityac95** [comment]
Thank you so much for looking into this and making the patch! Looking forward to trying out the new version when it's ready.

**Comment by napulen** [comment]
Ok, it's out! `v1.7.1`

If you re-run your files with the latest code you should notice *some* improvement.

I still don't know what to do exactly about transposing instruments, I think that's going to be a harder problem. But this should help for now.

**Comment by napulen** [comment]
By the way, @adityac95, as you mentioned you are only interested in the chord labels. 

You already have them in the lyrics of the `_annotated.xml`, below the RNA. I recommend parsing the chord labels from those lyrics.
